# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Блог Азата Заляева
tagline:             'Заметки о путешествиях, жизни за рубежом и маркетинге'
description:         'Здесь будет описание, которое показывается при открытии меню'
url:                 http://richaz.ru
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Azat Zalyaev
  url:               
  email:             azat.success@gmail.com
