# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Richaz.online
tagline:             'Заметки о жизни, путешествиях и маркетинге'
description:         'Чтобы удобнее было находить информацию среди постов можно выбрать нужный раздел'
url:                 http://richaz.online
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Азат Заляев
  url:               www.facebook.com/zalyaev
  email:             azat.success@gmail.com
